// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

const getStorageKey = () => {
  try {
    const hostname = new URL(SUPABASE_URL).hostname;
    const projectRef = hostname.split('.')[0];
    return projectRef ? `sb-${projectRef}-auth-token` : undefined;
  } catch {
    return undefined;
  }
};

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error("Variáveis do Supabase ausentes: VITE_SUPABASE_URL ou VITE_SUPABASE_ANON_KEY.");
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    storageKey: getStorageKey(),
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});
